# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ckb rpc ci test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Run Test
      if: always()
      run: mvn clean test -Dmaven.test.failure.ignore=true site
      continue-on-error: true

    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: main
        path: main

    - name: Allure Report action from marketplace
        uses: actions/checkout@v3
        if: always()
        run: mvn io.qameta.allure:allure-maven:serve && mvn io.qameta.allure:allure-maven:report
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: main
          allure_report: allure-report
          allure_history: allure_history

    - name: Deploy report to Github Pages
        uses: actions/checkout@v3
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          PUBLISH_BRANCH: main
          PUBLISH_DIR: allure-history

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
